#ifndef COMM_TYPE__
#define COMM_TYPE__

#include <stdint.h>
#include <assert.h>
#include <stdlib.h>
#include "../Libs/tlv.h"

#define COORD_IP_ADDR 2130706433 // 127.0.0.1
#define COORD_UDP_PORT 40000

/*TLV definitions*/
#define TLV_CODE_NAME 1
#define TLV_CODE_NAME_LEN 32
#define TLV_IPC_NET_SKT_LEN 6
#define TLV_IPC_TYPE_MSGQ 2  // TLV size 2 Bytes
#define TLV_IPC_TYPE_UXSKT 3 // TLV size 2 Bytes
#define TLV_IPC_TYPE_CBK 4
#define TLV_IPC_NET_UDP_SKT 5
#define TLV_IPC_TYPE_MSGQ_LEN 32
#define TLV_IPC_TYPE_UXSKT_LEN 32
#define TLV_IPC_TYPE_CBK_LEN (sizeof(uintptr_t))
#define TLV_DATA_128 6
#define TLV_DATA_256 7

typedef enum
{
    SUBS_TO_COORD,
    COORD_TO_SUBS,
    PUB_TO_COORD,
    COORD_TO_PUB,

} msg_type_t;

typedef enum
{
    SUB_MSG_DATA,       // Data generated by publisher to be conveyed to coordinator
    SUB_MSG_ADD,        // publisher publishes a new message or subscriber subscribes a new message
    SUB_MSG_DELETE,     // publiser unpublishes a mesaage or subscriber unscribes a message
    SUB_MSG_REGISTER,   // subscriber or publisher register or unregister a massge
    SUB_MSG_UNREGISTER, // subscriber or publisher register or unregister a massge
    SUB_MSG_ID_ALLOC_SUCCESS,
    SUB_MSG_IPC_CHANNEL_ADD,
    SUB_MSG_IPC_CHANNEL_REMOVE,
    SUB_MSG_ERROR, // error

} sub_msg_type_t;

typedef enum
{
    IPC_TYPE_NONE,
    IPC_TYPE_NETSKT,
    IPC_TYPE_MSGQ,
    IPC_TYPE_UXSKT,
    IPC_TYPE_SHM,
    IPC_TYPE_CBK,

} ipc_type_t;

typedef enum
{
    CMSG_PR_HI,
    CMSG_PR_MID,
    CMSG_PR_LOW,
    CMSG_PR_MAX,
} cmsg_pr_t;

typedef enum
{
    ERROR_TLV_MISSING
} error_codes_t;
typedef struct cmsg_
{
    /*
     *if msg is generated by subsciber/publisher, assign msg ID 0, if this msg reaches
     *coordiantor, coordiantor assign a unique ID to it
     *unique ID : allocated by coordiantor only
     */
    uint32_t msg_id;
    /*Message type:
     *from pub to coordinator
     *from sub to coord
     *from coord to pub
     *from coord to sub
     * */
    msg_type_t msg_type;
    /*
     * Register msg or unregister msg
     * simple Data mgs: generated by publiser
     * Subscriber Msg ADD: subscriber tells coordinator I want to subscribe this message
     * Subscirber Msg DEL: subscriber tells coordiantor I don't want to subscriber this message any more
     * */
    sub_msg_type_t sub_msg_type;
    cmsg_pr_t priority;

    uint32_t msg_code; // actually it's an ID of a message, which pub or sub tells coordinator I want to pub/sub/unpub/ubsub a message
    union
    {
        uint32_t publisher_id;
        uint32_t subscriber_id;
    } id;                     // I think it's better as pub_sub_id
    uint32_t ref_count;       // reference count similar smart pointer,
    uint16_t tlv_buffer_size; // this value represents tlv_buffer size below
    char tlv_buffer[0];

} cmsg_t;

/*convert enum to its corresponding string*/
static inline const char *msg_type_to_string(msg_type_t msg_type)
{
    const char *it = nullptr;
    switch (msg_type)
    {
    case SUBS_TO_COORD:

        it = "Subscribers to coordinator";
        return it;
    case COORD_TO_SUBS:
        it = "Coordinator to subscriber";
        return it;
    case PUB_TO_COORD:
        it = "Publisher to coordinator";
        return it;
    case COORD_TO_PUB:
        it = "Coordinator to publisher";
        return it;
    default:
        return nullptr;
    }
}

/*convert enum to its corresponding string*/
static inline const char *sub_msg_type_to_string(sub_msg_type_t sub_msg_type)
{
    const char *it = nullptr;
    switch (sub_msg_type)
    {
    case SUB_MSG_DATA:

        it = "Subscriber message data type";
        return it;
    case SUB_MSG_ADD:
        it = "Subscriber subscribe a new message";
        return it;
    case SUB_MSG_DELETE:
        it = "Subscriber unscribe a message";
        return it;
    case SUB_MSG_REGISTER:
        it = "Subscriber registers a message in coordinator";
        return it;
    case SUB_MSG_UNREGISTER:
        it = "Subscriber unregisters a message in coordinator";
        return it;
    case SUB_MSG_ERROR:
        it = "Subsriber message error";
        return it;
    default:
        return nullptr;
    }
}

static inline const char *tlv_str(int tlv_code_point)
{
    switch (tlv_code_point)
    {
    case TLV_CODE_NAME:
        return "TLV_CODE_NAME";
    case TLV_IPC_TYPE_MSGQ:
        return "TL_IPC_TYPE_MSGQ";
    case TLV_IPC_TYPE_UXSKT:
        return "TLV_IPC_TYPE_UXSKT";
    case TLV_IPC_TYPE_CBK:
        return "TLV_IPC_TYPE_CBK";
    case TLV_IPC_NET_UDP_SKT:
        return "TLV_IPC_NET_UDP_SKT";
    case TLV_DATA_128:
        return "TLV_DATA_128";
    case TLV_DATA_256:
        return "TLV_DATA_256";
    default:
        return "UNKOWN";
    }
}
static int tlv_data_len(int tlv_code_point)
{
    switch (tlv_code_point)
    {
    case TLV_CODE_NAME:
        return TLV_CODE_NAME_LEN;
    case TLV_IPC_TYPE_MSGQ:
        return 64;
    case TLV_IPC_TYPE_UXSKT:
        return 64;
    case TLV_IPC_TYPE_CBK:
        return sizeof(uintptr_t);
    case TLV_IPC_NET_UDP_SKT:
        return TLV_IPC_NET_SKT_LEN;
    case TLV_DATA_128:
        return 128;
    case TLV_DATA_256:
        return 256;
    }
    return 0;
}
static inline void cmsg_reference(cmsg_t *cmsg)
{
    cmsg->ref_count++;
}

// static inline function, placed in head file
static inline void cmsg_dereference(cmsg_t *cmsg)
{
    assert(cmsg->ref_count);
    cmsg->ref_count--;
    if (cmsg->ref_count)
    {
        return;
    }
    free(cmsg);
}

#endif